name: Upload Files to Branch 'dood'

on:
  push:
    branches:
      - main  # Menjalankan workflow saat ada push ke branch 'main'

jobs:
  upload_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install required libraries
      run: |
        python -m pip install --upgrade pip
        pip install zipfile shutil

    - name: Run Python script to split zip into batches
      run: |
        python split_zip.py  # Menjalankan script untuk membagi file zip menjadi batch

    - name: Commit and push batch zip files to 'dood' branch
      run: |
        # Mengonfigurasi user git
        git config --global user.name "Qodri588"
        git config --global user.email "mqodri588@gmail.com"
        
        # Checkout branch dood dan pastikan branch tersebut ada
        git fetch origin dood || git checkout --orphan dood
        
        # Tambahkan file batch zip ke staging area
        git add output/*

        # Commit file zip
        git commit -m "Add batch zip files"

        # Push perubahan ke branch 'dood'
        git push origin dood