name: Upload Files to Branch 'dood'

on:
  push:
    branches:
      - master  # Menjalankan workflow saat ada push ke branch 'main'

jobs:
  upload_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script to split zip into batches
      run: |
        python split_zip.py  # Menjalankan script untuk membagi file zip menjadi batch

    - name: Commit and push batch zip files to 'dood' branch
      run: |
        # Mengonfigurasi user git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Memeriksa apakah branch 'dood' ada, jika tidak maka buat dan checkout
        git fetch origin
        git checkout dood || git checkout -b dood
        
        # Tambahkan file batch zip ke staging area
        git add output/*

        # Commit file zip
        git commit -m "Add batch zip files"

        # Push perubahan ke branch 'dood'
        git push origin dood
