name: Build Hugo Partial

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Hugo Extended
    - name: Setup Hugo Extended
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"
        extended: true

    # Extract markdown.zip
    - name: Extract markdown.zip
      run: |
        unzip -o markdown.zip -d .

    # Split Folders into Batches of 1000
    - name: Split folders into batches
      run: |
        mkdir -p split_batches
        batch_size=1000
        batch_index=1
        count=0
        for folder in markdown/*; do
          if [ $((count % batch_size)) -eq 0 ]; then
            mkdir -p split_batches/video_$batch_index
            batch_index=$((batch_index + 1))
          fi
          mv "$folder" split_batches/video_$((batch_index - 1))
          count=$((count + 1))
        done

    # Clean content folder
    - name: Clean content folder
      run: |
        rm -rf content/*
        mkdir -p content

    # Move Batches into Content Folder
    - name: Move batches into content folder
      run: |
        mv split_batches/* content/

    # Build Hugo Site for Each Batch
    - name: Build Hugo site for each batch
      run: |
        for dir in content/*; do
          if [ -d "$dir" ]; then
            hugo --contentDir "$dir" --destination "public/$(basename $dir)"
          fi
        done

    # Zip the Output
    - name: Zip the output
      run: |
        zip -r output.zip public

    # Push Output to 'dood' Branch
    - name: Push output to dood branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b dood || git checkout dood
        mv output.zip public.zip
        git add public.zip
        git commit -m "Add build output"
        git push origin dood --force
