name: Build Hugo Site with Splits

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"

    # Extract markdown.zip
    - name: Extract markdown.zip
      run: |
        unzip -o markdown.zip -d markdown

    # Split Markdown into Batches of 1000 Folders
    - name: Split folders into batches
      run: |
        mkdir -p split_batches
        batch=1
        count=0
        for folder in markdown/*; do
          [ -d "$folder" ] || continue
          target="split_batches/video_$batch"
          mkdir -p "$target"
          mv "$folder" "$target"
          count=$((count + 1))
          if [ "$count" -ge 1000 ]; then
            count=0
            batch=$((batch + 1))
          fi
        done

    # Remove all content in 'content' folder
    - name: Clean content folder
      run: |
        rm -rf content/*
        mkdir -p content

    # Move Split Batches into Content
    - name: Move batches into content folder
      run: |
        mv split_batches/* content/

    # Build Hugo Site for Each Batch
    - name: Build Hugo site for each batch
      run: |
        for dir in content/*; do
          if [ -d "$dir" ]; then
            hugo --contentDir "$dir" --destination "public/$(basename $dir)"
          fi
        done

    # Zip the Output
    - name: Zip the output
      run: |
        zip -r output.zip public

    # Push Output to 'dood' Branch
    - name: Push output to dood branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b dood || git checkout dood
        mv output.zip public.zip
        git add public.zip
        git commit -m "Add build output"
        git push ori
