name: Build Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"

    # Extract Markdown ZIP
    - name: Extract markdown.zip
      run: |
        unzip -o markdown.zip -d extracted

    # Split Markdown Files into Batches
    - name: Split Markdown files
      run: |
        chmod +x ./split
        ./split

    # Remove All Content in 'content' Folder
    - name: Clean content folder
      run: |
        rm -rf content/*
        mkdir -p content

    # Move Batches into Content Folder and Rename
    - name: Move batches into content and rename
      run: |
        for batch in markdown_batch_*; do
          new_name=$(echo $batch | sed 's/markdown_batch_/video/')
          mv "$batch" "content/$new_name"
        done

    # Build Hugo Site for Each Batch
    - name: Build Hugo site for each batch
      run: |
        for dir in content/*; do
          if [ -d "$dir" ]; then
            hugo --contentDir "$dir" --destination "public/$(basename $dir)"
          fi
        done

    # Zip Output
    - name: Zip the output
      run: |
        zip -r output.zip public

    # Push to 'dood' Branch
    - name: Push output to dood branch
      uses: actions/upload-artifact@v3
      with:
        name: public-output
        path: output.zip

    - name: Checkout dood branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b dood || git checkout dood

    - name: Upload zip to dood branch
      run: |
        mv output.zip public.zip
        git add public.zip
        git commit -m "Add build output"
        git push origin dood --force
